apiVersion: batch/v1
kind: Job
metadata:
  name: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 6
  template:
    spec:
      containers:
      - command:
        - 'sh'
        - '-c'
        - "echo 'Migration in progress...'; sleep 10; echo 'Done!'"
        image: busybox
        name: migration-job
